title: "Fábrica de Conteúdo"
description: "Pipeline de posts e carrosséis a partir de arquivos .md"
timezone: America/Manaus

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: "content/carrossel"
    values:
      layout: carrossel
      type: carrossel

  - scope:
      path: "content/static"
    values:
      layout: static
      type: static

exclude:
  - README.md
  - LICENSE